version: "3.7"

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn OSTrino_API.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=OSTrino_API.settings.production
    depends_on:
      - db

  proxy:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:8080"
    depends_on:
      - web

  db:
    image: "postgres:12-alpine"
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  db-init:
    image: "${DB_INIT_IMAGE}"
    env_file:
      - ./.env.prod
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=OSTrino_API.settings.production
    depends_on:
      - db

volumes:
  static_volume:
  postgres_data:
