version: "3.7"

volumes:
  static_volume:
  postgres_data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn OSTrino_API.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=OSTrino_API.settings.production
    depends_on:
      - postgres

  proxy:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:8080"
    depends_on:
      - web

  postgres:
    image: "postgres:12-alpine"
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  db-init:
    build:
      context: .
      dockerfile: db-init/Dockerfile
    image: "${DB_INIT_IMAGE}"
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=OSTrino_API.settings.production
    depends_on:
      - postgres
