version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn OSTrino_API.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=OSTrino_API.settings.production
    depends_on:
      - db

  proxy:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:8080"
      - "1337:80"
    depends_on:
      - app

  db:
    image: "${POSTGRES_IMAGE}"
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data:
