# Generated by Django 2.0.7 on 2018-10-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ost',
            name='video_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
