# Generated by Django 2.1.4 on 2020-05-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0002_auto_20190420_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ostdb.Tag'),
        ),
    ]
