# Generated by Django 2.1.4 on 2019-01-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0002_auto_20190123_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
