# Generated by Django 2.0.7 on 2018-10-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0002_auto_20181006_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ost',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostdb.Show'),
        ),
        migrations.RemoveField(
            model_name='ost',
            name='tags',
        ),
        migrations.AddField(
            model_name='ost',
            name='tags',
            field=models.ManyToManyField(to='ostdb.Tag'),
        ),
    ]
