# Generated by Django 2.1.4 on 2020-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0003_auto_20200521_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ost',
            name='spotify_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ost',
            name='video_id',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
