# Generated by Django 2.0.3 on 2018-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0003_auto_20181006_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
