# Generated by Django 2.0.3 on 2018-10-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0004_auto_20181016_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
