# Generated by Django 2.0.3 on 2018-11-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostdb', '0006_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='osts',
            field=models.ManyToManyField(default=None, to='ostdb.OST'),
        ),
    ]
